apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  annotations:
    sidecar.speedscale.com/inject: "true"
    sidecar.speedscale.com/tls-out: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: ksiig/error-handling
        ports:
        - containerPort: 3000
